stages:
  - dependencies
  - gegl

variables:
  BABL_DIR: "_babl_install"
  BABL_PREFIX: "$CI_PROJECT_DIR/$BABL_DIR"

cache:
  paths:
  - _pacman_cache

image: archlinux/base:latest

.babl-base:
  stage: dependencies
  artifacts:
    paths:
    - $BABL_DIR
  variables:
    GIT_DEPTH: "5"
  before_script:
    - pacman -Syu --noconfirm --needed --cachedir `pwd`/_pacman_cache git base-devel meson lcms2 gobject-introspection
    - git clone --depth=$GIT_DEPTH https://gitlab.gnome.org/GNOME/babl.git _babl
    - cd _babl
    - mkdir _build

babl-master:
  extends: .babl-base
  variables:
    GIT_STRATEGY: none
  script:
    - meson -Dprefix="$BABL_PREFIX" _build
    - ninja -C _build
    - ninja -C _build install

babl-min:
  extends: .babl-base
  script:
    - grep babl ../meson.build | grep version | grep -o '[0-9]*\.[0-9]*\.[0-9]*' | sed 's/\./_/g' > .babl_min_version
    - if [ x$(( $(cut .babl_min_version -f 3 -d _) % 2)) = x1 ] ; then touch .use_master ; fi
    - test -e .use_master && git fetch
    - test -e .use_master && git checkout master
    - test -e .use_master || git fetch --no-tags origin "refs/tags/BABL_`cat .babl_min_version`:refs/tags/MIN_VERSION"
    - test -e .use_master || git checkout MIN_VERSION
    - meson -Dprefix="$BABL_PREFIX" _build
    - ninja -C _build
    - ninja -C _build install


.build-gegl:
  stage: gegl
  variables:
    GIT_DEPTH: "15"
  before_script:
    - pacman -Syu --noconfirm --needed --cachedir `pwd`/_pacman_cache
        base-devel ccache meson
        ffmpeg
        gobject-introspection
        gobject-introspection-runtime
        jasper
        json-glib
        lcms2
        libgexiv2
        libraw
        librsvg
        libspiro
        libtiff
        luajit
        openexr
        python
        sdl2
        suitesparse
        vala
  script:
   - export XDG_DATA_DIRS="$XDG_DATA_DIRS:$BABL_PREFIX/share:/usr/local/share/:/usr/share/"
   - export PKG_CONFIG_PATH=$BABL_PREFIX/lib/pkgconfig
   - export LD_LIBRARY_PATH="$BABL_PREFIX/lib:$LD_LIBRARY_PATH"
   - meson -Dprefix="$BABL_PREFIX" $CONFIG_OPTIONS _build
   - LD_LIBRARY_PATH="$BABL_PREFIX/lib:$LD_LIBRARY_PATH"
     ninja -C _build
   - LD_LIBRARY_PATH="$BABL_PREFIX/lib:$LD_LIBRARY_PATH"
     ninja -C _build install

.build-default:
  extends: .build-gegl
  variables:
    CONFIG_OPTIONS: ""

.build-all:
  extends: .build-gegl
  variables:
    CONFIG_OPTIONS: "-Dworkshop=true -Ddocs=true -Dintrospection=true"

default-min-babl:
  extends: .build-default
  dependencies:
    - babl-min
  needs: ["babl-min"]

fullconfig-master-babl:
  extends: .build-all
  dependencies:
    - babl-master
  needs: ["babl-master"]
